# Generated by Django 4.2.4 on 2023-10-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='estimate_hours',
            new_name='estimated_hours',
        ),
    ]
