# Generated by Django 4.2.4 on 2023-10-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20231023_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
