# Generated by Django 4.2.4 on 2023-10-24 09:17

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoes')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    unique_brands_names = shoe.objects.values_list('brand', flat=True).distinct()

    # v1
    unique_brands_instances_list = [unique_brands(brand_name=unique_brand) for unique_brand in unique_brands_names]
    unique_brands.objects.bulk_create(unique_brands_instances_list)

    # v2
    # for brand_name in unique_brands_names:
    #     unique_brands.create(brand_name=brand_name)


def delete_create_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, delete_create_unique_brands)
    ]
