# Generated by Django 4.2.4 on 2023-10-25 04:51

from django.db import migrations


def place_age_groups(apps, schema_editor):
    person_obj = apps.get_model('main_app', 'Person')

    persons_all = person_obj.objects.all()
    for person_info in persons_all:
        if person_info.age <= 12:
            person_info.age_group = 'Child'
        elif person_info.age <= 17:
            person_info.age_group = 'Teen'
        else:
            person_info.age_group = 'Adult'

    person_obj.objects.bulk_update(persons_all, ['age_group'])


def delete_placed_age_groups(apps, schema_editor):
    person_obj = apps.get_model('main_app', 'Person')

    persons_all = person_obj.objects.all()
    age_group_default = person_obj._meta.get_field('age_group').default

    for person_info in persons_all:
        person_info.age_group = age_group_default

    person_obj.objects.bulk_update(persons_all, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [migrations.RunPython(place_age_groups, delete_placed_age_groups)
                  ]
