# Generated by Django 4.2.4 on 2023-10-30 15:12

from django.db import migrations


def set_rarity_group(apps, schema_editor):
    items_obj = apps.get_model('main_app', 'Items')

    items_all = items_obj.objects.all()

    for item_obj_data in items_all:

        if item_obj_data.price <= 10:
            item_obj_data.rarity = 'Rare'

        elif 11 <= item_obj_data.price <= 20:
            item_obj_data.rarity = 'Very Rare'

        elif 21 <= item_obj_data.price <= 30:
            item_obj_data.rarity = 'Extremely Rare'

        else:
            item_obj_data.rarity = 'Mega Rare'

    items_obj.objects.bulk_update(items_all, ['rarity'])


def reverse_rarity_group(apps, schema_editor):
    items_obj = apps.get_model('main_app', 'Items')

    items_all = items_obj.objects.all()

    for item_obj_info in items_all:
        item_obj_info.rarity = 'empty'

    items_obj.objects.bulk_update(items_all,['rarity'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0012_items'),
    ]

    operations = [migrations.RunPython(set_rarity_group, reverse_rarity_group)
                  ]
