# Generated by Django 4.2.4 on 2023-10-30 19:12

from django.db import migrations
from django.utils import timezone


def set_by_status(apps, schema_editor):
    orders_obj = apps.get_model('main_app', 'Order')

    orders_all = orders_obj.objects.all()

    for order_data in orders_all:

        if order_data.status == 'Pending':
            order_data.delivery = order_data.order_date + timezone.timedelta(days=3)
            order_data.save()

        elif order_data.status == 'Completed':
            order_data.warranty = '24 months'
            order_data.save()

        elif order_data.status == 'Cancelled':
            order_data.delete()


def reverse_by_status(apps, schema_editor):
    orders_obj = apps.get_model('main_app', 'Order')

    orders_all = orders_obj.objects.all()

    for order_data in orders_all:
        if order_data.status == 'Pending':
            order_data.delivery = None

        elif order_data.status == 'Completed':
            order_data.warranty = 'No warranty'

        order_data.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [migrations.RunPython(set_by_status, reverse_by_status)
                  ]
